### ISSUE TITLE
rootsStepClosureStruct has its Sig at the end of the structure

### ISSUE THREAD

**Issue by thejayps** [Ravenbrook/mps#184]
rootsStepClosureStruct defined in walk.c has its Sig at the end of the structure. There's no apparent explanation of any reason why this is the case

**Comment by rptb1** [comment]
This line was introduced by Tony Mann in 1999 https://github.com/Ravenbrook/mps/blame/fcd9dcc0cb620fda093ce91aaffd1b3cec5c2799/code/walk.c#L159 .

The rootsStepClosureStruct is defined as an extension of the ScanStateStruct https://github.com/Ravenbrook/mps/blob/e697cebcb9a7c0a8e4a0aac496137b4840622fdd/code/walk.c#L146-L154 but the ScanStateStruct starts with its own signature https://github.com/Ravenbrook/mps/blob/e697cebcb9a7c0a8e4a0aac496137b4840622fdd/code/mpmst.h#L401-L403 so I believe this is a case of [design.mps.pool.struct.outer.sig](https://github.com/Ravenbrook/mps/blob/e697cebcb9a7c0a8e4a0aac496137b4840622fdd/design/pool.txt#struct-outer-sig) -- guarding the end of a structure because there's already a signature at the start.

A related case is https://github.com/Ravenbrook/mps/blob/master/code/mpmst.h#L45-L47

Both of these predate but really belong in [design.mps.sig](https://github.com/Ravenbrook/mps/blob/e697cebcb9a7c0a8e4a0aac496137b4840622fdd/design/sig.txt).  We should fix that.
