### ISSUE TITLE
Running `git status` gives annoying warnings about symbolic links

### ISSUE THREAD

**Issue by Techcable** [Ravenbrook/mps#73]
Hi! I use mps in my project as a git submodule.

However, running `git status` on the MPS repo gives the following (annoying) warnings:
````
warning: unable to access '.gitignore': Too many levels of symbolic links
warning: unable to access 'code/.gitignore': Too many levels of symbolic links
warning: unable to access 'code/w3mv/.gitignore': Too many levels of symbolic links
warning: unable to access 'manual/.gitignore': Too many levels of symbolic links
warning: unable to access 'tool/.gitignore': Too many levels of symbolic links
````

This isn't just a problem with submodules. It happens on the main MPS repo too.

It appears git doesn't like your symbolic link setup :(

This issue exists both on Linux (`git version 2.34.1`) and on my Mac (`git version 2.32.0 (Apple Git-132)`). I have not tested Windows.

**Comment by gareth-rees** [comment]
This "feature" was added in [Git 2.32](https://github.com/git/git/blob/master/Documentation/RelNotes/2.32.0.txt).

All, I can say is that it seems very rude of Git to insist on coming first over other version control systems, due to what sound like fairly trivial technical limitations. We point `.gitignore` at `.p4ignore` as the repo is mirrored between Perforce and Git, and we want to share the ignore rules between the two version control systems. I suppose that if Git is too feeble to cope, we could turn all the symlinks round so that `.p4ignore` is a symlink pointing at `.gitignore` instead.

**Comment by Techcable** [comment]
> @Techcable I've made a PR that swaps the ignore files (#74) — could you try it out and check that it works for you?

Works great, thank you :)

> I'd be interested to hear more about how you are using the MPS — please send us an e-mail at mps-staff@ravenbrook.com.

Mostly experimental stuff for now. I'll be sure to send you an email once I have something more concrete :)

I'm already very impressed by the high performance and small code size (and appreciate the switch to BSD licensing)
